ok so everything works amazing in this page, howwever whne clsing a thread on teh suers end (liek in the users support page) it says Unexpected token '<', "<!doctype "... is not valid JSON


here are some docker debug logs aswell
 | 2025-03-03 17:02:49,895 - pymongo.connection - DEBUG - {"clientId": {"$oid": "67c5cea8ce87034b66ca328d"}, "message": "Connection checked in", "serverHost": "ac-75jlsm4-lb.nmo0cjq.mongodb.net", "serverPort": 27017, "driverConnectionId": 2}         backend_service      | 2025-03-03 17:02:49,895 - app - ERROR - Exception on /support/my-chat/67c5e0b1ce87034b66ca3315/close [POST]     backend_service      | Traceback (most recent call last):                                                                              backend_service      |   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app                                backend_service      |     response = self.full_dispatch_request()                                                                     backend_service      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                     backend_service      |   File "/venv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request                    backend_service      |     rv = self.handle_user_exception(e)                                                                          backend_service      |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                          backend_service      |   File "/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 165, in wrapped_function              backend_service      |     return cors_after_request(app.make_response(f(*args, **kwargs)))                                            backend_service      |                                                 ^^^^^^^^^^^^^^^^^^                                              backend_service      |   File "/venv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request                    backend_service      |     rv = self.dispatch_request()                                                                                backend_service      |          ^^^^^^^^^^^^^^^^^^^^^^^                                                                                backend_service      |   File "/venv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request                         backend_service      |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]     backend_service      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                    backend_service      |   File "/app/routes/support_routes.py", line 252, in user_close_specific_thread                                 backend_service      |     socketio.emit('new_message', {                                                                              backend_service      |     ^^^^^^^^                                                                                                    backend_service      | NameError: name 'socketio' is not defined        
----

additonally- i need the create button for the create a thread (on tehusers edn) needs to be ina differetn spot of something becasue if you look at this image
![image](https://github.com/user-attachments/assets/b53bc453-c708-4004-bb0b-73a8581c1c6c)

it its cutt off/ half hidden- so we need to find an alternaive palce to put it and it can be smaller aswell idk- dont chnag any ofther part of teh disgn- and also the error sesm to be backend wise so we just need to sllighly fix teh backedn BUT DO NOT EDIT ANY PART OF TEH FRONTNEND FUCNTION WISE- WE STRICTLY JUST NEED TO REARANGE/EDIT THE CREATE THREAD BUTTON WHICH IS A DESIGN THING NOT FUCNTIONLITY SO DONT EDIT ANY ACTUAL FUCNTIONLITY PLEASE.
